server:
  port: 8081

spring:
  application:
    name: stop-service
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=3600s

gtfs:
  static:
    url: https://oct-gtfs-emasagcnfmcgeham.z01.azurefd.net/public-access/GTFSExport.zip

management:
  endpoints:
    web:
      exposure:
        include: health,info
